### ISSUE TITLE
What changes were made to get metrocop firing working?

### ISSUE THREAD

**Issue by Electromaster232** [SonicEraZoR/Portal-Base#4]
Hi,

I've been working on a similar branch of Source for a while and I cannot figure out why metrocops can't fire when compiled with Portal code. What changes did you make to get this working? All I've been able to figure out is it had something to do with either the VModel or the animstate getting corrupted but that might be wrong.

Thanks

**Comment by Electromaster232** [comment]
Nevermind, I just searched again and found the commit https://github.com/SonicEraZoR/Portal-Base/commit/593083a1511c548bff8907d682d5a5f0871eaadc

Based on the commit message, I can see you went through the same pain I did trying to get this working...

**Comment by SonicEraZoR** [comment]
Yeah, it was a pain to find. Funnily enough, this fix is listed on Valve Developer Wiki https://developer.valvesoftware.com/wiki/Fixing_AI_in_multiplayer#SetActivity.28.29.
