### ISSUE TITLE
Crash in ModSettingsPanel.cpp

### ISSUE THREAD

**Issue by klaymen1n** [SonicEraZoR/Portal-Base#8]
![image](https://user-images.githubusercontent.com/84157659/162636235-c73a5fef-e967-40bb-8bb9-e784b3520b95.png)
I can't fix it,because i don't have enough experience using vs

**Comment by SonicEraZoR** [comment]
https://github.com/SonicEraZoR/Portal-Base/blob/master/sp/game/hl2_with_ashpd/resource/ui/modsettingspanel.res check if you have this file, the game will crash without it
